202010 fix camelcasing issue inside Profile Model
klaviyo/php-klaviyo pull request #33
Opened 2020-10-07 09:46 UTC by kamil-klasicki

The profileModel class has its properties listed using camelCase notation. 
As we are now doing a a property check between '$this' and $properties, the values that use snake_casing such as first_name or last_name will be missed out. 

As the code uses camelCasing across the board, we should keep this consistent and so before checking if property exists, we should do a conversion to camelCase. 

This already happens inside of setAttributes() method, so the PR simply pulls out that logic and puts it in its own function. 
We can then call it before '!property_exists' to make sure all values align. 

<img width="631" alt="Screenshot 2020-10-07 at 10 44 15" src="https://user-images.githubusercontent.com/31895163/95315232-25588780-088a-11eb-9983-02bc84df13c0.png">
<img width="614" alt="Screenshot 2020-10-07 at 10 44 46" src="https://user-images.githubusercontent.com/31895163/95315237-2689b480-088a-11eb-8ba5-a94b76f566b3.png">

2020-10-07 15:19 UTC, klaviyojad commented
Ok so this 🐫 logic was already there and all your doing is making a special method and calling it somewhere we missed?

2020-10-07 15:51 UTC, kamil-klasicki commented
Yeah exactly, you can see that setAttributes method has the:
$this->{lcfirst(str_replace('_', '', ucwords(ltrim($key, '$'), '_')))} = $value;
has the logic that converts the snake case into camelCase so the properties are set correctly. 

We currently don't do it inside of json_Serialize, so when we do property_exists check, it will skip the ones that don't match
(first_name/firstName, last_name/lastName, phone_number/phoneNumber)

2020-10-07 16:08 UTC, klaviyojad approved these changes

2020-10-07 16:08 UTC, klaviyojad requested changes
The usual, update the version and README

2020-10-07 16:52 UTC, klaviyojad commented on CHANGELOG.md
> +- Fix - ProfileModel file to convert specialAttributes properties to camelCase before running property_exists inside jsonSerialize
```suggestion
- Fix - ProfileModel file to convert specialAttributes properties to camel case before executing property_exists method inside jsonSerialize
```

2020-10-07 16:53 UTC, klaviyojad approved these changes

2020-10-14 11:57 UTC, etienneroudeix approved these changes
Was just about to push the same PR :D

2020-10-14 12:10 UTC, merged